import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/src/components/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CitationMaster",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable}
        antialiased h-full max-w-lg m-auto p-4`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* <div className="flex flex-col gap-4">
            <div className="text-center">
              <NavigationMenuDemo />
            </div>
            <div className="text-center">
              <ModeToggle />
            </div>
            <div className="text-center">
              <MenubarDemo />
            </div>

            <Header />
            {children}
          </div> */}
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
